DROP TABLE IF EXISTS DEMO_ORDER;
CREATE TABLE DEMO_ORDER (
  SID BIGINT PRIMARY KEY AUTO_INCREMENT,
  VERSION_NO BIGINT,
  RGST_DATETIME DATETIME,
  UPDT_DATETIME DATETIME,
  VALUE  INT,
  STRING VARCHAR(255)
) ENGINE=InnoDB;

